"""empty message

Revision ID: 210999a7a207
Revises: dfc61a8b5524
Create Date: 2021-11-08 17:06:04.433888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '210999a7a207'
down_revision = 'dfc61a8b5524'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customer', 'postal_code',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('video', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('video', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('customer', 'postal_code',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
