"""empty message

Revision ID: 4dfc8258d9a2
Revises: cfc26f1b313c
Create Date: 2021-11-08 12:55:44.136387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dfc8258d9a2'
down_revision = 'cfc26f1b313c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('name', sa.String(), nullable=False))
    op.add_column('customer', sa.Column('phone', sa.String(length=13), nullable=True))
    op.add_column('customer', sa.Column('postal_code', sa.Integer(), nullable=True))
    op.add_column('customer', sa.Column('register_at', sa.DateTime(), nullable=True))
    op.add_column('video', sa.Column('release_date', sa.DateTime(), nullable=True))
    op.add_column('video', sa.Column('title', sa.String(), nullable=False))
    op.add_column('video', sa.Column('total_inventory', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video', 'total_inventory')
    op.drop_column('video', 'title')
    op.drop_column('video', 'release_date')
    op.drop_column('customer', 'register_at')
    op.drop_column('customer', 'postal_code')
    op.drop_column('customer', 'phone')
    op.drop_column('customer', 'name')
    # ### end Alembic commands ###
