"""empty message

Revision ID: dfc61a8b5524
Revises: 4dfc8258d9a2
Create Date: 2021-11-08 16:23:44.489152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfc61a8b5524'
down_revision = '4dfc8258d9a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customer', 'postal_code',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customer', 'postal_code',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
